language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.5
  - 5.4
  - 5.3

before_script:
    - composer self-update
    - composer --prefer-source --dev install
    - cp phpunit.xml.dist phpunit.xml

script: 
    - phpunit -c phpunit.xml Tests/
